"""TS{{NN}} {{NAME}} {{PLATFORM}} {{UNIVERSE_SPOKEN}} — live/paper/shadow runner.

Skeleton generated by bin/new-strategy. The lifecycle below is the contract every
strategy runner follows; see STRATEGY.md §5 and common/alerts/README.md.
"""
from __future__ import annotations

import logging
import os
import sys
import time
from pathlib import Path

__version__ = "0.1"
SLUG = "{{SLUG}}"
HERE = Path(__file__).resolve().parent.parent
log = logging.getLogger("TS{{NN}}")


def load_params():
    import yaml  # noqa: WPS433
    with open(HERE / "config" / "params.yaml") as f:
        return yaml.safe_load(f)


def assert_mode_allowed(params):
    """LIVE requires STRATEGY.md frontmatter live_approved and a change-log entry."""
    mode = str(params["mode"]).upper()
    if mode != "LIVE":
        return mode
    text = (HERE / "STRATEGY.md").read_text()
    fm = text.split("---")[1]
    approved = next((l.split(":", 1)[1].strip() for l in fm.splitlines()
                     if l.startswith("live_approved:")), "")
    if not approved:
        sys.exit("refusing LIVE: STRATEGY.md live_approved is empty")
    if approved not in text.split("## Change log")[-1]:
        sys.exit(f"refusing LIVE: live_approved {approved} not in change log")
    return mode


def cycle(state, exchange, alerts, params, mode):
    """One bar-close cycle. Order matters.

    1. reconcile   — exchange is truth; on mismatch alert and do nothing else
    2. evaluate    — stop / target / pool-consumed / window expiry on THIS bar
    3. detect      — new setups
    4. act         — PAPER: log; SHADOW: compose ticket + log; LIVE: place
    5. alert       — every message: MODE · EVENT · TS{{NN}} <variant> · signal ts
    """
    raise NotImplementedError("implement per STRATEGY.md §2–§5")


def main():
    logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO"),
                        format="%(asctime)s %(name)s %(levelname)s %(message)s")
    params = load_params()
    mode = assert_mode_allowed(params)
    log.info("starting %s v%s mode=%s", SLUG, __version__, mode)
    # from common.exchange import binance; from common.alerts import telegram
    while True:
        try:
            cycle(state=None, exchange=None, alerts=None, params=params, mode=mode)
        except NotImplementedError as e:
            log.error("%s", e)
            return 1
        except Exception:  # noqa: BLE001
            log.exception("cycle failed; continuing")
        time.sleep(params.get("poll_seconds", 30))


if __name__ == "__main__":
    sys.exit(main())
